#%RAML 1.0 NamedExample
value: [
   {
      "customerId": 1,
      "lastName": "Neerukonda",
      "firstName": "Aswani",
      "phoneNumber": "8328561368",
      "emailId" : "aswanineerukonda@gmail.com",
      "SSN" : "123-45-6789"
  }
  ,
  
  {
      "customerId": 2,
      "lastName": "nknd",
      "firstName": "Anu",
      "phoneNumber": "1234568",
      "emailId" : "anu@gmail.com",
      "SSN" : "123-45-1212"
  }
  
  ]